apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
  namespace: bgd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatapp
  strategy: {}
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: chatapp
        image: ghcr.io/joeangry/signalr-scale:0.0.2
        
        env:
          - name: App__RedisConnection
            valueFrom:
              configMapKeyRef:
                key: redis-host
                name: chatapp-config

          - name: ASPNETCORE_URLS
            value: http://*:8080

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
