apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: chatapp
  # Part of the route
  name: chatapp
  # Second part of the route
  namespace: bgd
spec:
  host: ""
  port:
    targetPort: 8080
  to:
    kind: Service
    # Target
    name: chatapp
    weight: 100
status: {}