apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgd
  namespace: bgd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgd
  template:
    metadata:
      labels:
        app: bgd
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: bgd
        image: ghcr.io/joeangry/signalr-scale:0.0.2
        
        env:
          - name: App__RedisConnection
            valueFrom:
              configMapKeyRef:
                key: redis-host
                name: bgd-config

          - name: ASPNETCORE_URLS
            value: http://localhost:8080

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
